version: '3'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - VERSION=v1
      - JWT_SECRET=thisisthesecretcrabbypattyrecipe
      - JWT_EXPIRY=1h